source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'
gem 'execjs'
gem 'therubyracer'
gem 'rails_admin'
gem 'paperclip', :git => 'git://github.com/thoughtbot/paperclip.git'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem "httparty"
gem 'hoptoad_notifier' 
gem 'tinymce_hammer'
#gem "ruby-debug19"
gem "awesome_print"
#gem install ruby-debug
gem "airbrake"
gem "simple-navigation"
#gem "cancan"

#gem 'will_paginate', '~> 3.0'
#gem "google-geocoder", "~> 0.1.0"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

